Repository tientrinh21/exchangelicious, pull requests merged in 2024-04, with the labels that each got.

#6 3 configure the database schema
  README.md
  client/.gitignore
  client/app/components/consumeApiDemo.tsx
  client/app/datatypes/datatypes.tsx
  client/app/layout.tsx
  client/app/page.tsx
  server/.gitignore
  server/__pycache__/db_helper_functions.cpython-312.pyc
  server/database_schemas/countries.sql
  server/database_schemas/schema.sql
  server/db.py
  server/requirements.txt
  server/server.py
Labels: backend

#15 Refactoring navigation bar
  client/app/components/main-nav.tsx
  client/app/components/mobile-nav.tsx
  client/app/favicon.ico
  client/app/globals.css
  client/app/layout.tsx
  client/app/not-found.tsx
  client/app/page.tsx
  client/components/consumeApiDemo.tsx
  client/components/main-nav.tsx
  client/components/mobile-nav.tsx
  client/components/site-header.tsx
  client/components/site-logo.tsx
  client/components/ui/button.tsx
  client/components/ui/dropdown-menu.tsx
  client/lib/utils.ts
  client/package-lock.json
  client/package.json
  client/tsconfig.json
  client/types/university.ts
  client/types/user.ts
Labels: enhancement, frontend

#21 #20 split server.py into different folders and files
  server/.gitignore
  server/__pycache__/db_helper_functions.cpython-312.pyc
  server/__pycache__/server.cpython-312.pyc
  server/__pycache__/server.cpython-38.pyc
  server/database/database_setup.py
  server/database/models.py
  server/resources_api/resource_fields_definitions.py
  server/resources_api/routes.py
  server/resources_api/universities.py
  server/resources_api/users.py
  server/server.py
  server/swagger_setup.py
Labels: backend

#18 User login
  server/database/database_setup.py
  server/resources_api/users.py
  server/server.py
  server/static/api_swagger_docs.json
Labels: enhancement, backend

#19 13 pagination on the university list overview
  client/app/page.tsx
  client/components/paginationDemo.tsx
  client/components/university-search-bar.tsx
  client/package-lock.json
  client/package.json
  server/database_schemas/schema.sql
  server/resources_api/resource_fields_definitions.py
  server/resources_api/routes.py
  server/resources_api/universities.py
  server/server.py
  server/static/api_swagger_docs.json
Labels: enhancement
